[build]
  publish = "frontend/public"
  functions = "netlify"

[dev]
  functions = "netlify"
  publish = "frontend/public"

[build.environment]
  NODE_VERSION = "20.16.0"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/:splat"
  status = 200
